### ISSUE TITLE
upgrade to Rust 2018

### ISSUE THREAD

**Issue by ubnt-intrepid** [ubnt-intrepid/dot#18]

**Comment by ingorichter** [comment]
I compiled it with 1.38.0 and made a small change to get rid of the warnings. My changes are here https://github.com/ingorichter/dot. Is there anything else?

**Comment by ubnt-intrepid** [comment]
If there is no `package.edition` in `Cargo.toml`, Cargo sets the edition to 2015 for compatibility. In order to use the edition 2018 explicitly, we need to set `edition = "2018"`. When the edition is upgraded, the build will probably fail caused by errors around module resolution.

[Here](https://doc.rust-lang.org/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html) is a guide for the transition to Rust 2018.

**Comment by ingorichter** [comment]
Okay, that makes more sense now ;-) I didn't know about the `edition` field. And now I can see the errors. Thanks for clarifying that. I'm going to resolve some of these issues.

**Comment by ingorichter** [comment]
@ubnt-intrepid I have a PR that enables Rust 2018 support
